-- ═══════════════════════════════════════════════════════════════════════════
-- Steel Port — schema inicial
--
-- Retrato fiel do banco de produção em 03/09/2026, extraído do catálogo do
-- Postgres. Serve para que uma branch do Supabase nasça idêntica à produção.
--
-- Esta migration NÃO muda nada: ela apenas descreve o que já existe, inclusive
-- as políticas "allow all" que a Fase 3 do plano vai substituir. A troca das
-- políticas virá numa migration própria, para poder ser revista e revertida
-- separadamente.
--
-- Descreve apenas as tabelas do Steel Port. O banco de produção ainda tem cinco
-- tabelas com prefixo wp_, de outro sistema (WoodPort), que tem banco próprio e
-- não pertence a este projeto — por isso ficam de fora desta migration.
-- ═══════════════════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────────────────
-- STEEL PORT · cadastro e acesso
-- ───────────────────────────────────────────────────────────────────────────

create table if not exists public.users (
  id        text primary key,
  nome      text,
  "user"    text,                       -- login; "user" é palavra reservada, daí as aspas
  pass      text,                       -- legado: sai na Fase 4 (já está vazia)
  role      text,                       -- admin | operator | viewer
  perms     text,                       -- JSON serializado das permissões por módulo
  email     text,
  passhash  text,                       -- SHA-256 do lado do cliente; sai na Fase 2
  armazens  jsonb default '[]'::jsonb   -- armazéns permitidos; vazio = todos
);

create table if not exists public.navios (
  nome text primary key
);

-- ───────────────────────────────────────────────────────────────────────────
-- STEEL PORT · bobinas
-- ───────────────────────────────────────────────────────────────────────────

-- Cadastro das bobinas. A chave é composta porque o mesmo número de bobina
-- pode se repetir entre navios e BLs diferentes.
create table if not exists public.coilsdb (
  coil     text not null,
  armazem  text,
  bl       text not null,
  cliente  text,
  navio    text not null,
  viagem   text,
  produto  text,
  pesob    text,
  pesol    text,
  id       bigint generated by default as identity,
  primary key (coil, navio, bl)
);

create unique index if not exists coilsdb_coil_navio_idx
  on public.coilsdb using btree (coil, navio);

-- Descargas e expedições de bobinas. O id é gerado no cliente (Date.now()),
-- por isso não há sequência; e "data" é text no formato AAAA-MM-DD — as
-- comparações do sistema são feitas como string.
create table if not exists public.records (
  id              bigint primary key,
  coil            text,
  data            text,
  periodo         text,
  bl              text,
  navio           text,
  veiculo         text,
  motorista       text,
  cliente         text,
  viagem          text,
  produto         text,
  pesob           text,
  pesol           text,
  armazem         text,
  obs             text,
  "registradoEm"  text,
  "registradoPor" text
);

create table if not exists public.expedicoes (
  id              bigint primary key,
  coil            text,
  data            text,
  periodo         text,
  bl              text,
  navio           text,
  veiculo         text,
  motorista       text,
  cliente         text,
  viagem          text,
  produto         text,
  pesob           text,
  pesol           text,
  armazem         text,
  obs             text,
  "registradoEm"  text,
  "registradoPor" text
);

-- ───────────────────────────────────────────────────────────────────────────
-- STEEL PORT · carga geral
-- ───────────────────────────────────────────────────────────────────────────

create table if not exists public.bulk_items (
  id         uuid primary key,
  bl         text,
  navio      text,
  cliente    text,
  produto    text,
  descricao  text,
  qtd_total  numeric,
  unidade    text,
  armazem    text,
  peso       numeric,
  created_at timestamptz default now()
);

create table if not exists public.bulk_descargas (
  id         uuid primary key,
  bl         text,
  descricao  text,
  quantidade numeric,
  data       date,
  periodo    text,
  veiculo    text,
  motorista  text,
  armazem    text,
  obs        text,
  navio      text,
  cliente    text,
  produto    text,
  unidade    text,
  created_at timestamptz default now(),
  created_by text,
  peso_kg    numeric default 0,
  destino    text default ''::text
);

create table if not exists public.bulk_expedicoes (
  id         uuid primary key,
  bl         text,
  descricao  text,
  quantidade numeric,
  data       date,
  periodo    text,
  veiculo    text,
  motorista  text,
  obs        text,
  navio      text,
  cliente    text,
  produto    text,
  unidade    text,
  created_at timestamptz default now(),
  created_by text,
  peso_kg    numeric default 0,
  destino    text default ''::text,
  armazem    text
);

-- Exclusões compartilhadas: é o que impede um dispositivo com dados antigos de
-- ressuscitar um registro que outro já apagou.
create table if not exists public.bulk_deletions (
  id         text primary key,
  tabela     text,
  deleted_at timestamptz default now(),
  deleted_by text
);

-- ───────────────────────────────────────────────────────────────────────────
-- STEEL PORT · faturamento, tickets e apoio
-- ───────────────────────────────────────────────────────────────────────────

-- Chave/valor do faturamento: tarifas, handling, pesos congelados e o estado de
-- cada período (state_<BL>_<n>). Passou de mil linhas — toda leitura precisa
-- ser paginada.
create table if not exists public.fat_config (
  chave text primary key,
  valor text
);

create table if not exists public.tickets (
  id         bigint primary key,
  ticket_num text,
  ts         timestamptz not null default now(),
  user_id    text,
  usuario    text,
  veiculo    text,
  motorista  text,
  destino    text,
  data       text,
  periodo    text,
  obs        text,
  entries    jsonb,
  tipo       text default 'EXP'::text     -- EXP | DSC | CGX | CGD
);

create table if not exists public.audit_log (
  id        bigint primary key,
  ts        timestamptz not null default now(),
  tipo      text,
  descricao text,
  usuario   text,
  user_id   text,
  snapshot  jsonb
);

-- Pesagens importadas da API do Porto de São Francisco
create table if not exists public.pesagens_porto (
  ticket              text primary key,
  pl_veiculo          text,
  placa_norm          text,
  dt_entrada          date,
  hr_entrada          text,
  dt_saida            date,
  hr_saida            text,
  peso_entrada        numeric,
  peso_saida          numeric,
  peso_liquido        numeric,
  documento           text,
  pasta               text,
  navio               text,
  operacao            text,
  nome_motorista      text,
  transportadora      text,
  cnpj_transportadora text,
  armazem_porto       text,
  pl_carreta1         text,
  observacao          text,
  bl                  text,
  exp_ids             text,
  nosso_peso          numeric,
  importado_por       text,
  importado_em        timestamptz default now()
);

create index if not exists idx_pesagens_porto_placa_data
  on public.pesagens_porto using btree (placa_norm, dt_saida);

-- Backups automáticos: cada linha guarda um retrato inteiro do sistema em texto.
-- Hoje são 690 linhas somando ~4,4 GB — ver a nota de retenção no plano.
create table if not exists public.backups (
  id      bigint primary key,
  ts      timestamptz not null default now(),
  label   text,
  size_kb integer,
  data    text,
  user_id text
);

-- ───────────────────────────────────────────────────────────────────────────
-- Proteção do faturamento
-- ───────────────────────────────────────────────────────────────────────────
-- Um cliente rodando código antigo conseguia sobrescrever a NF de um período
-- com "{}" e apagar o registro do faturamento. Este gatilho recusa esse UPDATE
-- no banco, independentemente da versão que o navegador estiver rodando.

create or replace function public.fat_config_bloqueia_wipe()
returns trigger
language plpgsql
as $function$
begin
  if new.chave like 'state\_%' and coalesce(new.valor,'') = '{}'
     and coalesce(old.valor,'') not in ('', '{}') then
    return old;
  end if;
  return new;
end $function$;

drop trigger if exists trg_fat_config_bloqueia_wipe on public.fat_config;
create trigger trg_fat_config_bloqueia_wipe
  before update on public.fat_config
  for each row execute function public.fat_config_bloqueia_wipe();

-- ───────────────────────────────────────────────────────────────────────────
-- Row Level Security
-- ───────────────────────────────────────────────────────────────────────────
-- A RLS já está LIGADA em todas as tabelas. O que deixa o banco aberto são as
-- políticas abaixo, que liberam tudo para qualquer um com a chave pública.
--
-- Elas estão reproduzidas aqui de propósito, para a branch nascer igual à
-- produção. A Fase 3 do plano substitui todas por regras baseadas em quem
-- está autenticado.

alter table public.users            enable row level security;
alter table public.navios           enable row level security;
alter table public.coilsdb          enable row level security;
alter table public.records          enable row level security;
alter table public.expedicoes       enable row level security;
alter table public.bulk_items       enable row level security;
alter table public.bulk_descargas   enable row level security;
alter table public.bulk_expedicoes  enable row level security;
alter table public.bulk_deletions   enable row level security;
alter table public.fat_config       enable row level security;
alter table public.tickets          enable row level security;
alter table public.audit_log        enable row level security;
alter table public.pesagens_porto   enable row level security;
alter table public.backups          enable row level security;

-- Steel Port
drop policy if exists "allow all" on public.users;
create policy "allow all" on public.users for all to public using (true) with check (true);

drop policy if exists "allow all" on public.navios;
create policy "allow all" on public.navios for all to public using (true) with check (true);

drop policy if exists "allow all" on public.coilsdb;
create policy "allow all" on public.coilsdb for all to public using (true) with check (true);

drop policy if exists "allow all" on public.records;
create policy "allow all" on public.records for all to public using (true) with check (true);

drop policy if exists "allow all" on public.expedicoes;
create policy "allow all" on public.expedicoes for all to public using (true) with check (true);

drop policy if exists "allow all" on public.tickets;
create policy "allow all" on public.tickets for all to public using (true) with check (true);

drop policy if exists "allow all" on public.audit_log;
create policy "allow all" on public.audit_log for all to public using (true) with check (true);

drop policy if exists "allow all" on public.backups;
create policy "allow all" on public.backups for all to public using (true) with check (true);

drop policy if exists "allow_all_bulk_items" on public.bulk_items;
create policy "allow_all_bulk_items" on public.bulk_items for all to public using (true) with check (true);

drop policy if exists "allow_all_bulk_descargas" on public.bulk_descargas;
create policy "allow_all_bulk_descargas" on public.bulk_descargas for all to public using (true) with check (true);

drop policy if exists "allow_all_bulk_expedicoes" on public.bulk_expedicoes;
create policy "allow_all_bulk_expedicoes" on public.bulk_expedicoes for all to public using (true) with check (true);

drop policy if exists "bulk_deletions_all" on public.bulk_deletions;
create policy "bulk_deletions_all" on public.bulk_deletions for all to anon, authenticated using (true) with check (true);

drop policy if exists "pesagens_porto_all" on public.pesagens_porto;
create policy "pesagens_porto_all" on public.pesagens_porto for all to public using (true) with check (true);

-- fat_config tem três políticas hoje; as duas de leitura são redundantes com a
-- "allow all" e serão removidas na Fase 3.
drop policy if exists "allow all" on public.fat_config;
create policy "allow all" on public.fat_config for all to public using (true) with check (true);

drop policy if exists "fat_config authenticated read" on public.fat_config;
create policy "fat_config authenticated read" on public.fat_config for select to authenticated using (true);

drop policy if exists "fat_config public read" on public.fat_config;
create policy "fat_config public read" on public.fat_config for select to anon, authenticated using (true);
